version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: nest-app
    ports:
      - "3010:3010"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped